---
title: "Research"
toc: false
---

## Johannah Palomo is a doctoral candidate in sociology at the University of North Carolina at Chapel Hill. 

I am a mixed methods researcher and a scholar of religion, gender, and well-being. I am interested in how individuals understand, interpret, and enact the teachings and policies of their religious organizations and the relationship between religiosity and well-being.

My three-paper dissertation uses quantiative and qualitative approaches to investigate the prevalence and health impacts of religious incongruence, or misalignment between personal and congregational beliefs, and explore how individuals, specifically Latter-day Saint women, perform the everyday embodied aesthetic work of communicating belonging within religious institutions through their appearance.

My master’s thesis uses data from the National Longitudinal Study of Adolescent to Adult Health to examine the reciprocal relationships between religious service attendance and depressive symptoms across the life course. As a Wagoner Foreign Study Fellow, I interviewed Latter-day Saint women in Ireland on their faith and experiences as members of the LDS Church and the church’s influence on their lives.

As a Graduate Teaching Fellow at UNC, I teach undergraduate courses in Sociology of Religion and Sociology of Mental Health and Illness. In 2026, I received the UNC Chapel Hill Department of Sociology’s Wilson-Aldrich Teaching Award.